# Generated by Django 4.1.7 on 2023-03-14 11:56

import common.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('usermanagement', '0002_family_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='family',
            managers=[
                ('objects', common.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
    ]
