# Generated by Django 4.1.7 on 2023-03-14 12:12

import common.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('usermanagement', '0003_alter_family_managers_family_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Alternate Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternate Email')),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_contact_detail', to='usermanagement.family', verbose_name='Family')),
                ('site', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Family Contact Detail',
                'verbose_name_plural': 'Family Contact Details',
                'ordering': ('-created',),
            },
            managers=[
                ('objects', common.managers.CurrentSiteManager()),
            ],
        ),
    ]
