# Generated by Django 4.1.7 on 2023-04-04 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Plan Name')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Plan Price')),
                ('max_members', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Members')),
                ('term', models.CharField(choices=[('per_month', 'per month'), ('per_year', 'per year')], default='per_month', max_length=10, verbose_name='Plan Term')),
                ('is_active', models.BooleanField(default=True, help_text='Is active or not', verbose_name='Is Active')),
                ('stripe_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe ID')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ('-created',),
            },
        ),
    ]
